# Project information
site_name: J/L2 Docs
site_url: https://vaxeman.github.io/l2docs/

# Navigation
nav: 
  - Home: index.md
  - DNS: 
    - 'Common records & lookup': dns.md
    - 'Differences Among A, CNAME, ALIAS, and URL records': difference-a-cname-alias.md
  - Networking:
    - 'IP address': networking/IP-address.md   
    - 'Ports': ports.md
    - 'Protocols': protocols.md  
    - 'Domains' : domains.md
    - 'Basic Tools': ping-traceroute-netstat.md
    - 'SSL': ssl.md
    - 'TCP/UDP': TCP-vs-UDP.md
    - 'ICMP' : icmp.md
    - 'OSI 7-layer model': internet-models.md
    - 'FTP': FTP.md
    - 'HTTP/HTTPS': HTTP-HTTPS.md
  - Linux:
    - 'Boot Process': linux/boot.md 
    - 'Permissions': linux/permissions.md
    - 'Piping': linux/piping.md
    - 'File Management': linux/file-management.md
    - 'Archiving and Compression': linux/archiving-compression.md
    - '.bashrc': linux/bashrc.md
    - 'VIM': linux/VIM.md
  - CMS: 
    - 'WordPress': wordpress.md
    - 'Magento': magento.md
  - Emails:  
    - Email : emails.md
    - Deliverability: deliverability.md
  
  - FAQ:
    - DNS: faq/what-dns.md
    - Emails: faq/what-emails.md
    - Networking: faq/what-networking.md
    - Linux: faq/what-linux.md
    - Magento: faq/what-magento.md
  
# Theme
theme:
  name: material
  features:
    - navigation.top
    - navigation.path
    - navigation.tracking    - 
    - navigation.expand
    - navigation.path
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    scheme: slate
    primary: lime
    accent: cyan    
  font:
      text: Roboto
      code: Roboto Mono  
markdown_extensions:
   - pymdownx.superfences
   - admonition
   - pymdownx.details
   - pymdownx.highlight
   - pymdownx.critic
   - pymdownx.caret
   - pymdownx.keys
   - pymdownx.mark
   - pymdownx.tilde
   - abbr
   - attr_list
   - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Plugins      
plugins:
    - search 
    - offline 
#    - encryptcontent:
#        title_prefix: ''
#        search_index: 'clear'
#        global_password: ${{ secrets.VAJFBITER }}
    

